# Generated by Django 5.1.1 on 2025-06-03 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostIDReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_date', models.DateField()),
                ('report_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Reported'), ('S', 'Resolved')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_id_reports', to='booking.refugee')),
            ],
        ),
        migrations.CreateModel(
            name='BirthCertificateBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_certificate_bookings', to='booking.refugee')),
            ],
        ),
    ]
