# Generated by Django 5.1.1 on 2025-06-13 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostDocumentsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID', 'Lost ID'), ('MANIFEST', 'Manifest')], max_length=10)),
                ('lost_date', models.DateField()),
                ('report_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Reported'), ('S', 'Resolved')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_documents_reports', to='booking.refugee')),
            ],
        ),
        migrations.CreateModel(
            name='LostIDDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100)),
                ('lost_document_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_details', to='booking.lostdocumentsreport')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(max_length=100)),
                ('lost_document_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_details', to='booking.lostdocumentsreport')),
            ],
        ),
        migrations.DeleteModel(
            name='LostIDReport',
        ),
    ]
